apiVersion: v1
kind: Service
metadata:
  name: number-verifier-service
  namespace: streaming-server
spec:
  type: ClusterIP
  ports:
    - port: 420
      targetPort: 420
  selector:
    name: number-verifier-pod
    