{{/* Copyright: (c) 2022, Justin Béra (@just1not2) <me@just1not2.org> */}}
{{/* Apache License 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0.txt) */}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "streama.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "streama.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "streama.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "streama.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "streama.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: streama-http
              containerPort: 8080
              protocol: TCP
          env:
            - name: STREAMA_MYSQL_HOST
              value: {{ include "streama.databaseHost" . }}
            - name: STREAMA_MYSQL_PORT
              value: {{ include "streama.databasePort" . }}
            - name: STREAMA_MYSQL_DB
              value: {{ include "streama.databaseName" . }}
            - name: STREAMA_MYSQL_USER
              value: {{ include "streama.databaseUser" . }}
            - name: STREAMA_MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "streama.databaseSecretName" . }}
                  key: mysql-password
          startupProbe:
            httpGet:
              path: /
              port: streama-http
            initialDelaySeconds: {{ .Values.probes.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.startup.timeoutSeconds }}
            successThreshold: {{ .Values.probes.startup.successThreshold }}
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /
              port: streama-http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            successThreshold: {{ .Values.probes.readiness.successThreshold }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          livenessProbe:
            httpGet:
              path: /
              port: streama-http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            successThreshold: {{ .Values.probes.liveness.successThreshold }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: streama-data
              mountPath: /data/streama
      volumes:
        - name: streama-data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "streama.fullname" .) }}
      {{- end -}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
