{{/* Copyright: (c) 2022, Justin Béra (@just1not2) <me@just1not2.org> */}}
{{/* Apache License 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0.txt) */}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "streama.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "streama.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: streama-http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "streama.selectorLabels" . | nindent 4 }}
