apiVersion: v1
kind: Service
metadata:
  name: streaming-server-service
spec:
  type: NodePort
  ports:
    - nodePort: 30000 
      port: 8080
      targetPort: 8080
  selector:
    name: streaming-server-pod
    