apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: kibana-np
spec:
  selector: 
    app: kibana
  type: NodePort  
  ports:
    - port: 8080
      targetPort: 5601 
      nodePort: 30000