apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: monitoring-logs
  name: fluentd
  labels:
    app: fluentd
rules:
- apiGroups:
    - ""
  resources:
    - pods
    - namespaces
  verbs:
    - get
    - list
    - watch