apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
  namespace: monitoring-traces
spec:
  type: NodePort
  ports:
    - name: ui
      protocol: TCP
      nodePort: 30003
      port: 16686
      targetPort: 16686
    - name: exporter-port
      protocol: TCP
      port: 4317
      targetPort: 4317
  selector:
    name: jaeger-pod
