apiVersion: v1
kind: Service
metadata:
  name: fibonacci-service
  namespace: streaming-server
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    name: fibonacci-pod
    